name: Resistors

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install Angular CLI
        run: npm install -g @angular/cli@9

      - name: Install dependencies
        run: npm install

      - name: Install Mocha
        run: npm install mocha --save-dev

      - name: Install Karma Firefox Launcher
        run: npm install karma-firefox-launcher --save-dev

      - name: Install Karma Spec Reporter
        run: npm install karma-spec-reporter --save-dev

      - name: Install Protractor
        run: npm install protractor --save-dev

      - name: Run Unit Tests
        run: ng test --watch=false --browsers=FirefoxHeadless

      - name: E2E test
        run: ng e2e || true

      - name: Build Docker image
        run: docker build -t my-angular-app .

      - name: Run Docker container
        run: docker run -d -p 8080:80 --name my-angular-app-container my-angular-app

      - name: Verify deployment
        run: |
          sleep 30 # Wait for the container to be fully up and running
          curl -f http://localhost:8080 || (docker logs my-angular-app-container && exit 1)

      - name: Cleanup Docker container and image
        if: always()
        run: |
          docker stop my-angular-app-container
          docker rm my-angular-app-container
          docker rmi my-angular-app
